### ISSUE TITLE
Consider using 'aiohttp' instead 'requests'.

### ISSUE THREAD

**Issue by 49MiB** [dimitrivlachos/Scarlet-discord-bot#23]
Hello, 
I noticed that the `requests` library is being used in the functions that call the APIs and I think it would be better to use `aiohttp` instead since it is already part of `discord.py`. This would reduce the number of dependencies, which is good. Additionally, `aiohttp` fits better in the codebase that involves asynchronous programming.

_-_ Victor

**Comment by dimitrivlachos** [comment]
That is a great suggestion @49MiB, I will look into it! Thank you!

**Comment by dimitrivlachos** [comment]
And I have now changed over to aiohttp. I think I could probably make the each function a bit better, but I'll get to that later, for now I've moved over to aiohttp at the very least 😄

**Comment by 49MiB** [comment]
I took a look and it turned out great, I wanted to make a pull request to help you with this work but I've been busy. Anyway, it's excellent and I apologize regardless, asynchronous things can be a bit tricky at times.

_-_ Victor

**Comment by dimitrivlachos** [comment]
Aw, sorry to have beaten you to the punch! I appreciate the thought though. I would never mind a PR to look over 💗

And thank you, I appreciate the positive feedback. Async stuff can get funky. I've pretty much spent the day re-writing the music cog to get the yt-dlp stuff to run asynchronously. But it's worth it in the end 💪
